# Generated by Django 4.0.1 on 2022-04-14 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certifications',
            name='user',
        ),
    ]
