# Generated by Django 4.0.1 on 2022-03-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nstpApp', '0004_alter_extenduser_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='extenduser',
            name='platoon',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
